### ISSUE TITLE
Question on the get_fes_running-metad.sh

### ISSUE THREAD

**Issue by yunjian-hash** [invemichele/opes#1]
Dear Dr. Invernizzi,

I have a question on the the get_fes_running-metad.sh. In this script, there is a file named 'bck.meup.sh', and it is not provided. Could you please provided for me so that I can run the get_fes_running-metad.sh. Thanks!

Best regards,
Yunjian

**Comment by invemichele** [comment]
Hi Yunjian,

you can find the file in the postprocessing folder, see https://github.com/invemichele/opes/blob/master/postprocessing/bck.meup.sh
