### ISSUE TITLE
Question about column number of cv

### ISSUE THREAD

**Issue by gongshuai0606** [invemichele/opes#2]
Hi, Does the `help='the CVs to be used. Either by name or by column number, starting from 1'` in the argument of cv in line 35 of opes/postprocessing /FES_from_Reweighting.py mean that cv column number can be 1? If so, the "name_cv_x" in line 95 will be fields[2] which is column time?

**Comment by invemichele** [comment]
It means that the column number starts from 1 and not from 0. Column 1 however is usually the time, which is not a CV
